# Generated by Django 3.1.4 on 2021-01-02 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.IntegerField(choices=[(0, 'CAT'), (1, 'DOG')], default=0, verbose_name='Type')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('img', models.URLField(max_length=600)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='animals.owners')),
            ],
        ),
    ]
